name: Deploy SQL Database

on:
  workflow_dispatch:

permissions:
  id-token: write   # Required for federated identity login
  contents: read

jobs:
  deploy-sql:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, uat, prod]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login via Federated Credentials
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy SQL Script to ${{ matrix.environment }}
        run: |
          echo "Deploying to ${{ matrix.environment }} environment..."
          sqlcmd -S ${{ secrets.AZURE_SQL_SERVER }} -d ${{ secrets.AZURE_SQL_DATABASE }} \
                 -U ${{ secrets.AZURE_SQL_USERNAME }} -P ${{ secrets.AZURE_SQL_PASSWORD }} \
                 -i ./scripts/deploy.sql
