name: SQL DB CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Dev
        run: |
          sqlcmd -S ${{ secrets.AZURE_SQL_SERVER }} -d ${{ secrets.AZURE_SQL_DATABASE }} -G -i ./sql/deploy.sql

  deploy-uat:
    needs: build
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to UAT
        run: |
          sqlcmd -S ${{ secrets.AZURE_SQL_SERVER_UAT }} -d ${{ secrets.AZURE_SQL_DATABASE_UAT }} -G -i ./sql/deploy.sql

  deploy-prod:
    needs: deploy-uat
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Prod
        run: |
          sqlcmd -S ${{ secrets.AZURE_SQL_SERVER_PROD }} -d ${{ secrets.AZURE_SQL_DATABASE_PROD }} -G -i ./sql/deploy.sql
